import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🏗️  Seeding products for Depósito Santa Inês...');

  // Find the Santa Inês organization
  const org = await prisma.organization.findFirst({
    where: { slug: 'santa-ines-deposito' },
  });

  if (!org) {
    console.error('❌ Organization santa-ines-deposito not found. Run seed-santa-ines.ts first.');
    return;
  }

  console.log(`📦 Adding products to: ${org.name} (ID: ${org.id})`);

  // ─── Products catalog based on typical São Paulo building materials depot ───
  const products = [
    // ═══════════════════════════════════════════════════════════════════════════
    // 1. CIMENTO (Cement)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Cimento CP-II-F 32',
      sku: 'CIM-001',
      category: 'CIMENTO',
      subcategory: 'Cimento Portland Composto',
      unit: 'sc 50kg',
      weightPerUnit: 50,
      volumePerUnit: 0.035,
      unitPrice: 32.90,
      brand: 'Votorantim',
      supplier: 'Votorantim Cimentos',
      description: 'Cimento Portland Composto com fíler calcário. Ideal para obras gerais, assentamento, reboco e concreto não estrutural.',
      certification: 'ABNT NBR 5736 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 40,
      shelfLifeDays: 90,
      isFragile: false,
      requiresSpecialHandling: true,
    },
    {
      name: 'Cimento CP-V-ARI 40',
      sku: 'CIM-002',
      category: 'CIMENTO',
      subcategory: 'Cimento Portland de Alta Resistência Inicial',
      unit: 'sc 50kg',
      weightPerUnit: 50,
      volumePerUnit: 0.035,
      unitPrice: 42.50,
      brand: 'Votorantim',
      supplier: 'Votorantim Cimentos',
      description: 'Cimento de alta resistência inicial, ideal para pré-moldados, pisos industriais e urgentes que exigem desforma rápida.',
      certification: 'ABNT NBR 5737 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 40,
      shelfLifeDays: 60,
      isFragile: false,
      requiresSpecialHandling: true,
    },
    {
      name: 'Cimento CPIV 32',
      sku: 'CIM-003',
      category: 'CIMENTO',
      subcategory: 'Cimento Portland de Alta Resistência a Sulfatos',
      unit: 'sc 50kg',
      weightPerUnit: 50,
      volumePerUnit: 0.035,
      unitPrice: 38.90,
      brand: 'InterCement',
      supplier: 'InterCement Brasil',
      description: 'Cimento resistente a sulfatos e águas agressivas. Ideal para fundações, tubulões e obras em contato com o solo.',
      certification: 'ABNT NBR 5735 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 40,
      shelfLifeDays: 90,
      isFragile: false,
      requiresSpecialHandling: true,
    },
    {
      name: 'Cimento CP-I 32',
      sku: 'CIM-004',
      category: 'CIMENTO',
      subcategory: 'Cimento Portland Comum',
      unit: 'sc 50kg',
      weightPerUnit: 50,
      volumePerUnit: 0.035,
      unitPrice: 29.90,
      brand: 'CSN Mineração',
      supplier: 'CSN Cimentos',
      description: 'Cimento Portland comum para uso geral em construções civis.',
      certification: 'ABNT NBR 5732 / INMETRO',
      qualityGrade: 'B',
      minStorageTemp: 5,
      maxStorageTemp: 40,
      shelfLifeDays: 90,
      isFragile: false,
      requiresSpecialHandling: true,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 2. AREIA (Sand)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Areia Média Lavada',
      sku: 'ARE-001',
      category: 'AREIA',
      subcategory: 'Agregado Natural',
      unit: 'm³',
      weightPerUnit: 1500,
      volumePerUnit: 1,
      unitPrice: 95.00,
      brand: null,
      supplier: 'Pirenópolis Materiais',
      description: 'Areia média lavada, granulometria entre 0.15mm e 2.36mm. Para assentamento, reboco e argamassas.',
      certification: 'ABNT NBR 7211',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Areia Grossa Lavada',
      sku: 'ARE-002',
      category: 'AREIA',
      subcategory: 'Agregado Natural',
      unit: 'm³',
      weightPerUnit: 1600,
      volumePerUnit: 1,
      unitPrice: 88.00,
      brand: null,
      supplier: 'Pirenópolis Materiais',
      description: 'Areia grossa lavada, granulometria entre 0.6mm e 4.75mm. Para concreto e chapisco.',
      certification: 'ABNT NBR 7211',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Areia Fina (Padrão)',
      sku: 'ARE-003',
      category: 'AREIA',
      subcategory: 'Agregado Natural',
      unit: 'm³',
      weightPerUnit: 1450,
      volumePerUnit: 1,
      unitPrice: 82.00,
      brand: null,
      supplier: 'Pirenópolis Materiais',
      description: 'Areia fina para reboco e acabamento. Módulo de finura entre 1.5 e 2.0.',
      certification: 'ABNT NBR 7211',
      qualityGrade: 'B',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Areia Podre (Pó de Pedra)',
      sku: 'ARE-004',
      category: 'AREIA',
      subcategory: 'Agregado Artificial',
      unit: 'm³',
      weightPerUnit: 1700,
      volumePerUnit: 1,
      unitPrice: 72.00,
      brand: null,
      supplier: 'Mairiporã Pedras',
      description: 'Areia podre (pó de pedra) para uso em contrapiso e bases.',
      certification: 'ABNT NBR 7211',
      qualityGrade: 'B',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 3. BRITA (Gravel / Crushed Stone)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Brita 0 (Granito)',
      sku: 'BRI-001',
      category: 'BRITA',
      subcategory: 'Agregado Britado',
      unit: 'm³',
      weightPerUnit: 1600,
      volumePerUnit: 1,
      unitPrice: 78.00,
      brand: null,
      supplier: 'Mairiporã Pedras',
      description: 'Brita 0, fração 0 a 1/4". Para argamassas, contrapiso e acabamento.',
      certification: 'ABNT NBR 7211',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Brita 1 (Granito)',
      sku: 'BRI-002',
      category: 'BRITA',
      subcategory: 'Agregado Britado',
      unit: 'm³',
      weightPerUnit: 1650,
      volumePerUnit: 1,
      unitPrice: 82.00,
      brand: null,
      supplier: 'Mairiporã Pedras',
      description: 'Brita 1, fração 1/4" a 1/2". Mais comum para concreto estrutural (FCK 25 a 35).',
      certification: 'ABNT NBR 7211',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Brita 2 (Granito)',
      sku: 'BRI-003',
      category: 'BRITA',
      subcategory: 'Agregado Britado',
      unit: 'm³',
      weightPerUnit: 1700,
      volumePerUnit: 1,
      unitPrice: 85.00,
      brand: null,
      supplier: 'Mairiporã Pedras',
      description: 'Brita 2, fração 1/2" a 1". Para fundações, radier e concreto de maior volume.',
      certification: 'ABNT NBR 7211',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Brita 3 (Basalto)',
      sku: 'BRI-004',
      category: 'BRITA',
      subcategory: 'Agregado Britado',
      unit: 'm³',
      weightPerUnit: 1800,
      volumePerUnit: 1,
      unitPrice: 90.00,
      brand: null,
      supplier: 'Mairiporã Pedras',
      description: 'Brita 3, fração 1" a 2". Para obras pesadas, barragens e fundações especiais.',
      certification: 'ABNT NBR 7211',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 4. BLOCOS E TIJOLAS (Blocks & Bricks)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Bloco de Concreto 19x19x39cm',
      sku: 'BLO-001',
      category: 'BLOCOS',
      subcategory: 'Bloco Estrutural',
      unit: 'un',
      weightPerUnit: 12,
      volumePerUnit: 0.014,
      unitPrice: 3.80,
      brand: 'Concremix',
      supplier: 'Concremix Mairiporã',
      description: 'Bloco de concreto 19x19x39cm, resistência 2.5 MPa. Para alvenaria estrutural e de vedação.',
      certification: 'ABNT NBR 15837 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 45,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Bloco de Concreto 14x19x39cm',
      sku: 'BLO-002',
      category: 'BLOCOS',
      subcategory: 'Bloco de Vedação',
      unit: 'un',
      weightPerUnit: 9,
      volumePerUnit: 0.010,
      unitPrice: 2.90,
      brand: 'Concremix',
      supplier: 'Concremix Mairiporã',
      description: 'Bloco de concreto 14x19x39cm para alvenaria de vedação. Furo único ou duplo.',
      certification: 'ABNT NBR 15837 / INMETRO',
      qualityGrade: 'B',
      minStorageTemp: 5,
      maxStorageTemp: 45,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Tijolo Baiano 6 Furos (Cerâmico)',
      sku: 'TIJ-001',
      category: 'BLOCOS',
      subcategory: 'Tijolo Cerâmico',
      unit: 'un',
      weightPerUnit: 2.5,
      volumePerUnit: 0.003,
      unitPrice: 0.85,
      brand: null,
      supplier: 'Cerâmica Mairiporã',
      description: 'Tijolo cerâmico baiano de 6 furos (9x19x19cm). Para alvenaria de vedação e fechamento.',
      certification: 'ABNT NBR 6540',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: false,
    },
    {
      name: 'Tijolo Baiano 8 Furos (Cerâmico)',
      sku: 'TIJ-002',
      category: 'BLOCOS',
      subcategory: 'Tijolo Cerâmico',
      unit: 'un',
      weightPerUnit: 3.0,
      volumePerUnit: 0.003,
      unitPrice: 0.95,
      brand: null,
      supplier: 'Cerâmica Mairiporã',
      description: 'Tijolo cerâmico baiano de 8 furos (9x19x24cm). Melhor isolamento acústico.',
      certification: 'ABNT NBR 6540',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 5. AÇO (Steel / Rebar)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Vergalhão CA-50 6.3mm (1/4")',
      sku: 'ACO-001',
      category: 'ACO',
      subcategory: 'Vergalhão de Aço',
      unit: 'barra 12m',
      weightPerUnit: 2.96,
      volumePerUnit: 0.0005,
      unitPrice: 22.50,
      brand: 'Gerdau',
      supplier: 'Gerdau Açominas',
      description: 'Vergalhão CA-50 fio 6.3mm, barra de 12m. Para armação de concreto em estruturas leves e estribos.',
      certification: 'ABNT NBR 7481 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -20,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Vergalhão CA-50 8.0mm (5/16")',
      sku: 'ACO-002',
      category: 'ACO',
      subcategory: 'Vergalhão de Aço',
      unit: 'barra 12m',
      weightPerUnit: 4.73,
      volumePerUnit: 0.0006,
      unitPrice: 35.80,
      brand: 'Gerdau',
      supplier: 'Gerdau Açominas',
      description: 'Vergalhão CA-50 fio 8.0mm, barra de 12m. Para vigas, pilares e lajes.',
      certification: 'ABNT NBR 7481 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -20,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Vergalhão CA-50 10.0mm (3/8")',
      sku: 'ACO-003',
      category: 'ACO',
      subcategory: 'Vergalhão de Aço',
      unit: 'barra 12m',
      weightPerUnit: 7.40,
      volumePerUnit: 0.0009,
      unitPrice: 55.90,
      brand: 'Gerdau',
      supplier: 'Gerdau Açominas',
      description: 'Vergalhão CA-50 fio 10.0mm, barra de 12m. Para vigas, pilares e fundação.',
      certification: 'ABNT NBR 7481 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -20,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Vergalhão CA-50 12.5mm (1/2")',
      sku: 'ACO-004',
      category: 'ACO',
      subcategory: 'Vergalhão de Aço',
      unit: 'barra 12m',
      weightPerUnit: 11.60,
      volumePerUnit: 0.0014,
      unitPrice: 87.50,
      brand: 'Gerdau',
      supplier: 'Gerdau Açominas',
      description: 'Vergalhão CA-50 fio 12.5mm, barra de 12m. Para estruturas pesadas, fundações e pilares.',
      certification: 'ABNT NBR 7481 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -20,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Treliça Laje H=12cm',
      sku: 'ACO-005',
      category: 'ACO',
      subcategory: 'Treliça',
      unit: 'barra 12m',
      weightPerUnit: 8.5,
      volumePerUnit: 0.012,
      unitPrice: 62.00,
      brand: 'ArcelorMittal',
      supplier: 'ArcelorMittal Fixações',
      description: 'Treliça para laje protendida H=12cm. Compostas de aço CA-60 com puncionadas.',
      certification: 'ABNT NBR 14762 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -20,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Malha Pop 4.2mm (Tela Soldada)',
      sku: 'ACO-006',
      category: 'ACO',
      subcategory: 'Malha Soldada',
      unit: 'm²',
      weightPerUnit: 1.45,
      volumePerUnit: 0.001,
      unitPrice: 12.80,
      brand: 'Bassanel',
      supplier: 'Bassanel Telas',
      description: 'Malha pop 4.2mm tela soldada para concreto armado em pisos e contrapisos.',
      certification: 'ABNT NBR 7482 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -20,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 6. ARGAMASSAS (Mortars)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Argamassa AC-II (Externa) 20kg',
      sku: 'ARG-001',
      category: 'ARGAMASSAS',
      subcategory: 'Argamassa Colante',
      unit: 'sac 20kg',
      weightPerUnit: 20,
      volumePerUnit: 0.016,
      unitPrice: 28.90,
      brand: 'Aral',
      supplier: 'Aral Cola',
      description: 'Argamassa colante AC-II para assentamento e fixação de cerâmicas e porcelanatos em áreas externas.',
      certification: 'ABNT NBR 13755 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 35,
      shelfLifeDays: 180,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Argamassa AC-I (Interna) 20kg',
      sku: 'ARG-002',
      category: 'ARGAMASSAS',
      subcategory: 'Argamassa Colante',
      unit: 'sac 20kg',
      weightPerUnit: 20,
      volumePerUnit: 0.016,
      unitPrice: 22.90,
      brand: 'Aral',
      supplier: 'Aral Cola',
      description: 'Argamassa colante AC-I para assentamento e fixação de cerâmicas e porcelanatos em áreas internas.',
      certification: 'ABNT NBR 13753 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 35,
      shelfLifeDays: 180,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Argamassa AC-III (Piso) 20kg',
      sku: 'ARG-003',
      category: 'ARGAMASSAS',
      subcategory: 'Argamassa Colante',
      unit: 'sac 20kg',
      weightPerUnit: 20,
      volumePerUnit: 0.016,
      unitPrice: 36.90,
      brand: 'Aral',
      supplier: 'Aral Cola',
      description: 'Argamassa colante AC-III para pisos sobre pisos, porcelanatos grandes e áreas molhadas.',
      certification: 'ABNT NBR 13754 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 35,
      shelfLifeDays: 180,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Chapisco Rudimento Acrílico 25kg',
      sku: 'ARG-004',
      category: 'ARGAMASSAS',
      subcategory: 'Chapisco',
      unit: 'lata 25kg',
      weightPerUnit: 25,
      volumePerUnit: 0.018,
      unitPrice: 68.00,
      brand: 'Sika',
      supplier: 'Sika Materiais de Construção',
      description: 'Chapisco rudimento acrílico para preparo de superfícies de concreto antes da aplicação de reboco.',
      certification: 'ABNT NBR 14941',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 35,
      shelfLifeDays: 365,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 7. HIDRÁULICA (Plumbing)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Tubo PVC Soldável 25mm (Água Fria)',
      sku: 'HID-001',
      category: 'HIDRAULICA',
      subcategory: 'Tubulação Água Fria',
      unit: 'barra 6m',
      weightPerUnit: 0.45,
      volumePerUnit: 0.001,
      unitPrice: 12.50,
      brand: 'Tigre',
      supplier: 'Tigre Materiais',
      description: 'Tubo PVC soldável marrom 25mm barra 6m, PN 25 para água fria residencial.',
      certification: 'ABNT NBR 14268 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: false,
    },
    {
      name: 'Tubo PVC Soldável 32mm (Água Fria)',
      sku: 'HID-002',
      category: 'HIDRAULICA',
      subcategory: 'Tubulação Água Fria',
      unit: 'barra 6m',
      weightPerUnit: 0.72,
      volumePerUnit: 0.001,
      unitPrice: 19.90,
      brand: 'Tigre',
      supplier: 'Tigre Materiais',
      description: 'Tubo PVC soldável marrom 32mm barra 6m, PN 25 para água fria residencial.',
      certification: 'ABNT NBR 14268 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: false,
    },
    {
      name: 'Tubo PVC Esgoto 100mm',
      sku: 'HID-003',
      category: 'HIDRAULICA',
      subcategory: 'Tubulação Esgoto',
      unit: 'barra 6m',
      weightPerUnit: 2.10,
      volumePerUnit: 0.003,
      unitPrice: 32.90,
      brand: 'Tigre',
      supplier: 'Tigre Materiais',
      description: 'Tubo PVC série normal branco 100mm barra 6m para rede de esgoto.',
      certification: 'ABNT NBR 7362 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: false,
    },
    {
      name: 'Registro de Pressão 3/4" (Gaveta)',
      sku: 'HID-004',
      category: 'HIDRAULICA',
      subcategory: 'Registros',
      unit: 'un',
      weightPerUnit: 0.35,
      volumePerUnit: 0.001,
      unitPrice: 18.90,
      brand: 'Deca',
      supplier: 'Deca Hidráulica',
      description: 'Registro de pressão gaveta 3/4" em latão com rosca. Para água fria.',
      certification: 'ABNT NBR 15777',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 8. ELÉTRICA (Electrical)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Fio Flexível 2.5mm² (Cx 100m)',
      sku: 'ELE-001',
      category: 'ELETRICA',
      subcategory: 'Fiação',
      unit: 'cx 100m',
      weightPerUnit: 3.2,
      volumePerUnit: 0.005,
      unitPrice: 89.90,
      brand: 'Cabel',
      supplier: 'Cabel Cabos Elétricos',
      description: 'Fio flexível de cobre 2.5mm² isolamento PVC. Para circuitos de tomadas (NBR 14624).',
      certification: 'ABNT NBR 14624 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 70,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Fio Flexível 4.0mm² (Cx 100m)',
      sku: 'ELE-002',
      category: 'ELETRICA',
      subcategory: 'Fiação',
      unit: 'cx 100m',
      weightPerUnit: 5.1,
      volumePerUnit: 0.005,
      unitPrice: 142.90,
      brand: 'Cabel',
      supplier: 'Cabel Cabos Elétricos',
      description: 'Fio flexível de cobre 4.0mm² isolamento PVC. Para circuitos de chuveiro e força.',
      certification: 'ABNT NBR 14624 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 70,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Fio Flexível 6.0mm² (Cx 100m)',
      sku: 'ELE-003',
      category: 'ELETRICA',
      subcategory: 'Fiação',
      unit: 'cx 100m',
      weightPerUnit: 7.6,
      volumePerUnit: 0.005,
      unitPrice: 212.90,
      brand: 'Cabel',
      supplier: 'Cabel Cabos Elétricos',
      description: 'Fio flexível de cobre 6.0mm² isolamento PVC. Para circuitos de força geral.',
      certification: 'ABNT NBR 14624 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 70,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Eletroduto Corrugado 25mm (Rolô 100m)',
      sku: 'ELE-004',
      category: 'ELETRICA',
      subcategory: 'Infraestrutura',
      unit: 'rolô 100m',
      weightPerUnit: 4.5,
      volumePerUnit: 0.008,
      unitPrice: 58.90,
      brand: 'Docol',
      supplier: 'Docol Elétrica',
      description: 'Eletroduto corrugado flexível 25mm para passagem de fios em instalações elétricas embutidas.',
      certification: 'ABNT NBR 15065 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Disjuntor DIN 2P 32A',
      sku: 'ELE-005',
      category: 'ELETRICA',
      subcategory: 'Proteção',
      unit: 'un',
      weightPerUnit: 0.15,
      volumePerUnit: 0.0002,
      unitPrice: 38.90,
      brand: 'Schneider',
      supplier: 'Schneider Electric',
      description: 'Disjuntor monopolar + neutro 2P 32A curva C para proteção de circuitos.',
      certification: 'ABNT NBR 14722 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 55,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Quadro de Distribuição 12 Circuitos',
      sku: 'ELE-006',
      category: 'ELETRICA',
      subcategory: 'Infraestrutura',
      unit: 'un',
      weightPerUnit: 1.2,
      volumePerUnit: 0.004,
      unitPrice: 45.90,
      brand: 'Ferraz',
      supplier: 'Ferraz Materiais',
      description: 'Quadro de distribuição 12 circuitos com barra de terra e porta fusível.',
      certification: 'ABNT NBR 14722',
      qualityGrade: 'B',
      minStorageTemp: -10,
      maxStorageTemp: 55,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 9. TINTAS E ACABAMENTOS (Paints & Finishes)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Tinta Látex Premium 25L (Branca)',
      sku: 'TIN-001',
      category: 'TINTAS',
      subcategory: 'Tinta Látex',
      unit: 'lata 25L',
      weightPerUnit: 30,
      volumePerUnit: 0.025,
      unitPrice: 189.90,
      brand: 'Suvinil',
      supplier: 'Suvinil - BASF',
      description: 'Tinta látex premium alta cobertura e lavável. Rendimento 10-12 m²/L.',
      certification: 'ABNT NBR 15636',
      qualityGrade: 'A',
      minStorageTemp: 10,
      maxStorageTemp: 35,
      shelfLifeDays: 730,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Massa Corrida PVA 25kg',
      sku: 'TIN-002',
      category: 'TINTAS',
      subcategory: 'Massa',
      unit: 'lata 25kg',
      weightPerUnit: 28,
      volumePerUnit: 0.022,
      unitPrice: 78.90,
      brand: 'Suvinil',
      supplier: 'Suvinil - BASF',
      description: 'Massa corrida PVA para acabamento de paredes secas internas. Alta rendibilidade.',
      certification: 'ABNT NBR 15581',
      qualityGrade: 'A',
      minStorageTemp: 10,
      maxStorageTemp: 35,
      shelfLifeDays: 365,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Massa Acrílica Externa 25kg',
      sku: 'TIN-003',
      category: 'TINTAS',
      subcategory: 'Massa',
      unit: 'lata 25kg',
      weightPerUnit: 30,
      volumePerUnit: 0.022,
      unitPrice: 115.90,
      brand: 'Suvinil',
      supplier: 'Suvinil - BASF',
      description: 'Massa acrílica para reboco externo e regularização. Resistente à água e intempéries.',
      certification: 'ABNT NBR 15077',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 35,
      shelfLifeDays: 365,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Selador Acrílico 25L',
      sku: 'TIN-004',
      category: 'TINTAS',
      subcategory: 'Selador',
      unit: 'lata 25L',
      weightPerUnit: 28,
      volumePerUnit: 0.025,
      unitPrice: 109.90,
      brand: 'Coral',
      supplier: 'Coral - Sherwin-Williams',
      description: 'Selador acrílico concentrado para selagem de superfícies novas antes da pintura.',
      certification: 'ABNT NBR 15310',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 35,
      shelfLifeDays: 730,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 10. COBERTURA (Roofing)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Telha Cerâmica Romana',
      sku: 'COB-001',
      category: 'COBERTURA',
      subcategory: 'Telha Cerâmica',
      unit: 'un',
      weightPerUnit: 3.2,
      volumePerUnit: 0.018,
      unitPrice: 4.90,
      brand: 'Eternit',
      supplier: 'Eternit S.A.',
      description: 'Telha cerâmica tipo romana. Medida: 33x42cm, inclinação mínima 30%.',
      certification: 'ABNT NBR 15300 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: false,
    },
    {
      name: 'Telha Fibrocimento 6mm (2.44x1.10m)',
      sku: 'COB-002',
      category: 'COBERTURA',
      subcategory: 'Fibrocimento',
      unit: 'chapa',
      weightPerUnit: 14.5,
      volumePerUnit: 0.016,
      unitPrice: 42.90,
      brand: 'Eternit',
      supplier: 'Eternit S.A.',
      description: 'Chapa de fibrocimento sem amianto 6mm. Medida: 2.44m x 1.10m.',
      certification: 'ABNT NBR 15215 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: true,
    },
    {
      name: 'Telha Metálica Galvanizada (Barra 6m)',
      sku: 'COB-003',
      category: 'COBERTURA',
      subcategory: 'Telha Metálica',
      unit: 'barra 6m',
      weightPerUnit: 12.0,
      volumePerUnit: 0.015,
      unitPrice: 89.90,
      brand: 'ArcelorMittal',
      supplier: 'ArcelorMittal',
      description: 'Telha galvanizada ondulada barra 6m x 0.90m. Espessura 0.50mm, galvanização G90.',
      certification: 'ABNT NBR 6645',
      qualityGrade: 'A',
      minStorageTemp: -20,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 11. PISOS E REVESTIMENTOS (Flooring & Coatings)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Porcelanato Retificado 60x60cm (Cx 4un)',
      sku: 'PIS-001',
      category: 'PISOS',
      subcategory: 'Porcelanato',
      unit: 'cx',
      weightPerUnit: 32,
      volumePerUnit: 0.014,
      unitPrice: 189.90,
      brand: 'Eliane',
      supplier: 'Eliane Revestimentos',
      description: 'Porcelanato retificado 60x60cm, alto tráfego. 4 peças por caixa = 1.44m².',
      certification: 'ABNT NBR 13818 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 40,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: true,
    },
    {
      name: 'Cerâmica Esmaltada 20x20cm (Cx 20un)',
      sku: 'PIS-002',
      category: 'PISOS',
      subcategory: 'Cerâmica',
      unit: 'cx',
      weightPerUnit: 24,
      volumePerUnit: 0.012,
      unitPrice: 78.90,
      brand: 'Cecrisa',
      supplier: 'Cecrisa Revestimentos',
      description: 'Cerâmica esmaltada 20x20cm para parede, cozinha e banheiro.',
      certification: 'ABNT NBR 13816 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 40,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: true,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 12. ADITIVOS E QUÍMICOS (Additives & Chemicals)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Plastificante Líquido 5L',
      sku: 'ADI-001',
      category: 'ADITIVOS',
      subcategory: 'Plastificante',
      unit: 'un',
      weightPerUnit: 5.5,
      volumePerUnit: 0.005,
      unitPrice: 32.90,
      brand: 'Sika',
      supplier: 'Sika Materiais de Construção',
      description: 'Plastificante líquido para redução de água e melhoria de trabalhabilidade do concreto.',
      certification: 'ABNT NBR 14928',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 40,
      shelfLifeDays: 365,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Impermeabilizante Acrílico 25L',
      sku: 'ADI-002',
      category: 'ADITIVOS',
      subcategory: 'Impermeabilizante',
      unit: 'lata 25L',
      weightPerUnit: 30,
      volumePerUnit: 0.025,
      unitPrice: 168.90,
      brand: 'Sika',
      supplier: 'Sika Materiais de Construção',
      description: 'Impermeabilizante acrílico líquido para lajes, muros, fundações e áreas de serviço.',
      certification: 'ABNT NBR 15575',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 35,
      shelfLifeDays: 545,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 13. SISTEMAS DE FIXAÇÃO (Fixing Systems)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Parafuso para Drywall 25mm (Cx 1000)',
      sku: 'FIX-001',
      category: 'FIXACAO',
      subcategory: 'Parafusos',
      unit: 'cx 1000',
      weightPerUnit: 2.5,
      volumePerUnit: 0.003,
      unitPrice: 48.90,
      brand: 'Fischer',
      supplier: 'Fischer Fixações',
      description: 'Parafuso autofurante para drywall 3.5x25mm. Caixa com 1000 unidades.',
      certification: 'ABNT NBR 14840',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Bucha Nylon 8x60mm (Cx 200)',
      sku: 'FIX-002',
      category: 'FIXACAO',
      subcategory: 'Buchas',
      unit: 'cx 200',
      weightPerUnit: 1.0,
      volumePerUnit: 0.001,
      unitPrice: 28.90,
      brand: 'Fischer',
      supplier: 'Fischer Fixações',
      description: 'Bucha nylon expansão 8x60mm para fixação em alvenaria e concreto.',
      certification: 'ABNT NBR 14840',
      qualityGrade: 'A',
      minStorageTemp: -10,
      maxStorageTemp: 60,
      shelfLifeDays: null,
      isFragile: false,
      requiresSpecialHandling: false,
    },
    {
      name: 'Ancoragem Química 300ml',
      sku: 'FIX-003',
      category: 'FIXACAO',
      subcategory: 'Ancoragem',
      unit: 'cápsula 300ml',
      weightPerUnit: 0.45,
      volumePerUnit: 0.0003,
      unitPrice: 58.90,
      brand: 'Fischer',
      supplier: 'Fischer Fixações',
      description: 'Resina epóxi bicomponente para ancoragem química em concreto e alvenaria.',
      certification: 'ABNT NBR 15763 / ETA',
      qualityGrade: 'A',
      minStorageTemp: 5,
      maxStorageTemp: 35,
      shelfLifeDays: 365,
      isFragile: false,
      requiresSpecialHandling: false,
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // 14. JARDIM E MANUTENÇÃO (Garden & Maintenance)
    // ═══════════════════════════════════════════════════════════════════════════
    {
      name: 'Porta de Madeira 2.10x0.80m',
      sku: 'JAR-001',
      category: 'MADEIRA',
      subcategory: 'Portas',
      unit: 'un',
      weightPerUnit: 28,
      volumePerUnit: 0.05,
      unitPrice: 289.00,
      brand: 'Portobello',
      supplier: 'Portobello Soluções',
      description: 'Porta interna madeira maciça eucalipto 2.10x0.80m. Sem pintura (bruta).',
      certification: 'ABNT NBR 7646',
      qualityGrade: 'B',
      minStorageTemp: 5,
      maxStorageTemp: 40,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: true,
    },
    {
      name: 'Vidro Liso 4mm (Chapa 2.0x1.0m)',
      sku: 'JAR-002',
      category: 'VIDRO',
      subcategory: 'Vidro Liso',
      unit: 'chapa',
      weightPerUnit: 20,
      volumePerUnit: 0.008,
      unitPrice: 65.90,
      brand: 'Cebrace',
      supplier: 'Cebrace Vidros',
      description: 'Vidro liso 4mm chapa 2.0x1.0m para janelas e divisorias.',
      certification: 'ABNT NBR 13853 / INMETRO',
      qualityGrade: 'A',
      minStorageTemp: 0,
      maxStorageTemp: 50,
      shelfLifeDays: null,
      isFragile: true,
      requiresSpecialHandling: true,
    },
  ];

  // Insert products
  let created = 0;
  let skipped = 0;

  for (const product of products) {
    try {
      const exists = await prisma.product.findUnique({
        where: {
          name_organizationId: {
            name: product.name,
            organizationId: org.id,
          },
        },
      });

      if (exists) {
        console.log(`  ⏭️  Product already exists: ${product.name}`);
        skipped++;
        continue;
      }

      await prisma.product.create({
        data: {
          ...product,
          organizationId: org.id,
        },
      });
      console.log(`  ✅ Created: ${product.name} (${product.sku}) [${product.category}]`);
      created++;
    } catch (err: any) {
      console.error(`  ❌ Failed to create ${product.name}: ${err.message}`);
    }
  }

  console.log('');
  console.log('═══════════════════════════════════════════════════════════════');
  console.log(`🏗️  Depósito Santa Inês - Products Seeding Complete`);
  console.log(`   ✅ Created: ${created} products`);
  console.log(`   ⏭️  Skipped: ${skipped} products (already exist)`);
  console.log(`   📦 Total:   ${created + skipped} products cataloged`);
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('');
  console.log('📊 Categories:');
  const categories = Array.from(new Set(products.map(p => p.category)));
  for (const cat of categories) {
    const count = products.filter(p => p.category === cat).length;
    console.log(`   ${cat}: ${count} products`);
  }
  console.log('');
  console.log('🏆 Brands represented:');
  const brands = Array.from(new Set(products.map(p => p.brand).filter(Boolean)));
  for (const brand of brands) {
    console.log(`   • ${brand}`);
  }
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
